[build-system]
requires = [
  "hatchling",
  "hatch-requirements-txt",
  "hatch-fancy-pypi-readme>=22.5.0",
]
build-backend = "hatchling.build"

[project]
name = "gradio_pdf_redaction"
version = "0.0.25"
description = "Easily display PDFs in Gradio. Forked from Freddy Boulton's gradio_pdf repo."
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [{ name = "Sean Pedrick-Case", email = "spedrickcase@lambeth.gov.uk" }]
keywords = [
  "Documents",
  "PDF",
  "Document QA",
  "gradio",
  "gradio custom component",
  "gradio-template-Fallback"
]
# Add dependencies here
dependencies = ["gradio>=6.0,<7.0"]
classifiers = [
  'Development Status :: 3 - Alpha',
  'License :: OSI Approved :: Apache Software License',
  'Operating System :: OS Independent',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3 :: Only',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: 3.11',
  'Programming Language :: Python :: 3.12',
  'Programming Language :: Python :: 3.13',
  'Topic :: Scientific/Engineering',
  'Topic :: Scientific/Engineering :: Artificial Intelligence',
  'Topic :: Scientific/Engineering :: Visualization',
]

[project.optional-dependencies]
dev = ["build", "twine"]

[project.urls]
repository = "https://github.com/seanpedrick-case/gradio-pdf"
space = "https://huggingface.co/spaces/seanpedrick-case/gradio_pdf"

[tool.hatch.build]
artifacts = ["/backend/gradio_pdf_redaction/templates", "*.pyi", "backend/gradio_pdf_redaction/templates", "backend/gradio_pdf_redaction/templates"]

[tool.hatch.build.targets.wheel]
packages = ["/backend/gradio_pdf_redaction"]
